## Demonstration of Bulk2Space on demo1 dataset

### Import Bulk2Space

In [ ]:
from bulk2space import Bulk2Space
model = Bulk2Space()

### Decompose bulk-seq data into scRNA-seq data

Train β-VAE model to generate scRNA-seq data

In [2]:
generate_sc_meta, generate_sc_data = model.train_vae_and_generate(
    input_bulk_path='tutorial/data/example_data/demo1/demo1_bulk.csv',
    input_sc_data_path='tutorial/data/example_data/demo1/demo1_sc_data.csv',
    input_sc_meta_path='tutorial/data/example_data/demo1/demo1_sc_meta.csv',
    input_st_data_path='tutorial/data/example_data/demo1/demo1_st_data.csv',
    input_st_meta_path='tutorial/data/example_data/demo1/demo1_st_meta.csv',
    ratio_num=1,
    top_marker_num=500,
    gpu=0,
    batch_size=512,
    learning_rate=1e-4,
    hidden_size=256,
    epoch_num=20,
    vae_save_dir='tutorial/data/example_data/demo1/predata/save_model',
    vae_save_name='demo1_vae',
    generate_save_dir='tutorial/data/example_data/demo1/predata/output',
    generate_save_name='demo1')

loading data......
load data done!
begin vae training...

Train Epoch: 19: 100%|█| 20/20 [00:01<00:00, 15.25it/s, loss=0.5252, min_lo

min loss = 0.5252203941345215
vae training done!

generating: 100%|███████████████████| 249/249.0 [00:00<00:00, 12262.75it/s]

save trained vae in tutorial/data/example_data/demo1/predata/save_model/demo1_vae.pth.
generating....
generated done!

saving to tutorial/data/example_data/demo1/predata/output/demo1_celltype_pred.csv and tutorial/data/example_data/demo1/predata/output/demo1_data_pred.csv.

In [3]:
generate_sc_meta

      Cell       Cell_type
0      C_1          T cell
1      C_2  Dendritic cell
2      C_3        Monocyte
3      C_4          T cell
4      C_5          T cell
..     ...             ...
244  C_245  Dendritic cell
245  C_246  Dendritic cell
246  C_247  Dendritic cell
247  C_248  Dendritic cell
248  C_249  Dendritic cell

[249 rows x 2 columns]

In [4]:
generate_sc_data

,C_1,C_2,C_3,C_4,C_5,C_6,C_7,C_8,C_9,C_10,...,C_240,C_241,C_242,C_243,C_244,C_245,C_246,C_247,C_248,C_249
AP2B1,0.626690,0.613905,0.713269,0.560173,0.669750,0.590490,0.650834,0.531286,0.680752,0.544410,...,0.546440,0.510871,0.619274,0.640492,0.649933,0.569230,0.483362,0.550280,0.584756,0.583562
ZCCHC10,0.303225,0.286319,0.403583,0.225366,0.358619,0.394472,0.405909,0.260239,0.429008,0.250870,...,0.340657,0.292923,0.313093,0.289614,0.361022,0.297599,0.282961,0.407848,0.528228,0.335327
ARF3,0.528737,0.505512,0.564077,0.443419,0.434200,0.591801,0.448409,0.476640,0.524426,0.486490,...,0.536649,0.435973,0.506175,0.491610,0.588768,0.379734,0.474200,0.438772,0.448839,0.420401
ELOA,0.114385,0.158002,0.205178,0.122117,0.243502,0.107239,0.199565,0.116714,0.168558,0.185430,...,0.138138,0.111177,0.192235,0.204547,0.167974,0.103650,0.202754,0.210220,0.080866,0.289888
TNRC6C,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SLC25A24,0.506901,0.664801,0.735292,0.502766,0.558032,0.590491,0.610373,0.525088,0.850940,0.512380,...,0.614196,0.544365,0.670417,0.585746,0.758227,0.441655,0.605955,0.602100,0.747606,0.635365
INTS13,0.065622,0.000000,0.082370,0.072101,0.026869,0.034036,0.070905,0.000000,0.063085,0.016441,...,0.082803,0.075601,0.062031,0.084564,0.007624,0.042771,0.000000,0.018147,0.041473,0.012413
TIMM17A,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.018179,0.000000,0.000000,...,0.040960,0.110996,0.068087,0.000000,0.000000,0.009947,0.000000,0.000000,0.000000,0.088244
PSMC1,0.306773,0.298457,0.408020,0.217292,0.305006,0.387245,0.435506,0.268307,0.421335,0.280133,...,0.255140,0.390590,0.282728,0.367992,0.466199,0.314051,0.309177,0.332197,0.411840,0.388353
TAF2,0.111933,0.086029,0.189509,0.139594,0.107850,0.000000,0.023603,0.033048,0.071503,0.062142,...,0.016894,0.009459,0.013466,0.134478,0.028923,0.000000,0.039175,0.044957,0.197445,0.047653

Load trained β-VAE model to generate scRNA-seq data

In [5]:
generate_sc_meta, generate_sc_data = model.load_vae_and_generate(
    input_bulk_path='tutorial/data/example_data/demo1/demo1_bulk.csv',
    input_sc_data_path='tutorial/data/example_data/demo1/demo1_sc_data.csv',
    input_sc_meta_path='tutorial/data/example_data/demo1/demo1_sc_meta.csv',
    input_st_data_path='tutorial/data/example_data/demo1/demo1_st_data.csv',
    input_st_meta_path='tutorial/data/example_data/demo1/demo1_st_meta.csv',
    vae_load_dir='tutorial/data/example_data/demo1/predata/save_model/demo1_vae.pth',
    generate_save_dir='tutorial/data/example_data/demo1/predata/output', 
    generate_save_name='demo1_new',
    ratio_num=1,
    top_marker_num=500)

loading data......
load data done!
loading model from tutorial/data/example_data/demo1/predata/save_model/demo1_vae.pth

generating: 100%|███████████████████| 249/249.0 [00:00<00:00, 10229.01it/s]

generating....
generated done!

saving to tutorial/data/example_data/demo1/predata/output/demo1_new_celltype_pred.csv and tutorial/data/example_data/demo1/predata/output/demo1_new_data_pred.csv.
generating done!

### Decompose spatial barcoding-based spatial transcriptomics data into spatially resolved single-cell transcriptomics data

Train deep-forest model to generate spatially resolved single-cell transcriptomics data

In [6]:
df_meta, df_data = model.train_df_and_spatial_deconvolution(
    generate_sc_meta,
    generate_sc_data,
    input_st_data_path='tutorial/data/example_data/demo1/demo1_st_data.csv',
    input_st_meta_path='tutorial/data/example_data/demo1/demo1_st_meta.csv',
    spot_num=500,
    cell_num=10,
    df_save_dir='tutorial/data/example_data/demo1/predata/save_model/',
    df_save_name='deom1_df',
    map_save_dir='tutorial/data/example_data/demo1/result', 
    map_save_name='demo1',
    top_marker_num=500,
    marker_used=True,
    k=10)

sucessfully create positive data
sucessfully create negative data
select top 500 marker genes of each cell type...
df training....
df training done!
saving model to tutorial/data/example_data/demo1/predata/save_model/deom1_df
Calculating scores...
Calculating scores done.
saving result to tutorial/data/example_data/demo1/result/meta_demo1_10.csv and tutorial/data/example_data/demo1/result/data_demo1_10.csv

In [7]:
df_meta

,Cell,Cell_type,Spot,Spot_xcoord,Spot_ycoord,Cell_xcoord,Cell_ycoord
0,C_1,B cell,spot_1,1,1,0.61,1.05
1,C_2,B cell,spot_1,1,1,0.68,1.02
2,C_3,B cell,spot_1,1,1,0.69,1.22
3,C_4,B cell,spot_1,1,1,1.00,0.99
4,C_5,B cell,spot_1,1,1,1.22,1.43
...,...,...,...,...,...,...,...
295,C_296,T cell,spot_30,6,5,5.97,5.14
296,C_297,T cell,spot_30,6,5,5.86,4.89
297,C_298,T cell,spot_30,6,5,6.01,4.80
298,C_299,T cell,spot_30,6,5,5.99,4.92
299,C_300,T cell,spot_30,6,5,5.72,5.24

In [8]:
df_data

,C_1,C_2,C_3,C_4,C_5,C_6,C_7,C_8,C_9,C_10,...,C_291,C_292,C_293,C_294,C_295,C_296,C_297,C_298,C_299,C_300
AP2B1,0.551140,0.511488,0.593195,0.576938,0.448166,0.415174,0.656614,0.617198,0.475501,0.510463,...,0.642503,0.593879,0.531076,0.644040,0.669001,0.575536,0.469552,0.608471,0.659234,0.565981
ZCCHC10,0.315443,0.374871,0.330939,0.294685,0.314067,0.270877,0.274084,0.366185,0.339098,0.248326,...,0.364554,0.297093,0.276444,0.416151,0.398022,0.275490,0.279077,0.279088,0.366457,0.417272
ARF3,0.359342,0.392298,0.507921,0.505656,0.403107,0.498203,0.565495,0.513118,0.383681,0.436774,...,0.454542,0.546011,0.488633,0.427603,0.517613,0.445533,0.373182,0.445369,0.435678,0.447184
ELOA,0.067560,0.229501,0.177380,0.186041,0.120105,0.164673,0.169406,0.136022,0.155850,0.092914,...,0.130504,0.176778,0.075936,0.158921,0.092179,0.084736,0.118555,0.132977,0.186482,0.159606
TNRC6C,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SLC25A24,0.578674,0.718034,0.571746,0.587206,0.479055,0.491108,0.633153,0.555980,0.549757,0.604473,...,0.651694,0.605676,0.560210,0.626944,0.616136,0.647410,0.540254,0.538774,0.572326,0.563487
INTS13,0.064606,0.026134,0.053499,0.003328,0.034701,0.030928,0.000000,0.028906,0.078968,0.085228,...,0.141381,0.060039,0.000000,0.047941,0.039139,0.062180,0.040085,0.021166,0.039630,0.098883
TIMM17A,0.039689,0.000000,0.000000,0.000000,0.015341,0.029058,0.000000,0.008774,0.038951,0.013716,...,0.091295,0.057587,0.000000,0.019175,0.000000,0.000000,0.039309,0.000000,0.000000,0.049319
PSMC1,0.320129,0.363346,0.264099,0.287297,0.247534,0.352588,0.317047,0.330250,0.332154,0.270806,...,0.391447,0.456650,0.336007,0.360899,0.458542,0.319293,0.328148,0.304128,0.347973,0.339366
TAF2,0.128389,0.054639,0.121119,0.068572,0.097251,0.131143,0.129462,0.112830,0.044634,0.061607,...,0.000000,0.056689,0.133845,0.054585,0.049949,0.095288,0.083900,0.090769,0.094586,0.102988

Load trained deep-forest model to generate spatially resolved single-cell transcriptomics data

In [10]:
df_meta, df_data = model.load_df_and_spatial_deconvolution(
    generate_sc_meta,
    generate_sc_data,
    input_st_data_path='tutorial/data/example_data/demo1/demo1_st_data.csv',
    input_st_meta_path='tutorial/data/example_data/demo1/demo1_st_meta.csv',
    spot_num=500,
    cell_num=10,
    df_load_dir='tutorial/data/example_data/demo1/predata/save_model/deom1_df',
    map_save_dir='tutorial/data/example_data/demo1/result',  # file_dir
    map_save_name='demo1_new',  # file_name
    top_marker_num=500,
    marker_used=True,
    k=10)

sucessfully create positive data
sucessfully create negative data
select top 500 marker genes of each cell type...
loading model from tutorial/data/example_data/demo1/predata/save_model/deom1_df
Calculating scores...
Calculating scores done.
saving result to tutorial/data/example_data/demo1/result/meta_demo1_new_10.csv and tutorial/data/example_data/demo1/result/data_demo1_new_10.csv